# Generated by Django 3.1.1 on 2020-09-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200907_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='human_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя для шаблона'),
        ),
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=50, null=True, verbose_name='Стиль для шаблона'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тег'),
        ),
    ]
