# Generated by Django 3.1.1 on 2020-09-10 13:40

from django.db import migrations, IntegrityError
import json


def make_ingredient_dict(ingredient):
    fields = {
        'title': None,
        'dimension': None,
    }

    for key, value in ingredient.items():
        fields[key] = value
    return fields


def load_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('main', "Ingredient")
    db_alias = schema_editor.connection.alias
    with open('ingredients.json', encoding='utf-8') as file:
        ingredients = json.load(file)
        for ingredient in ingredients:
            try:
                fields = make_ingredient_dict(ingredient)
                Ingredient.objects.using(db_alias).create(
                    title=fields['title'],
                    dimension=fields['dimension'],
                )
            except IntegrityError:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200910_1340'),
    ]

    operations = [
        migrations.RunPython(load_ingredients)
    ]
