# Generated by Django 3.1.1 on 2020-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200913_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='human_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя для шаблона'),
        ),
    ]
